project_identifier: PROJECT_IDENTIFIER_CROWDIN
api_key: API_KEY_CROWDIN
pull_request_title: New Crowdin updates
pull_request_labels:
  - do-not-merge
base_path: ./
preserve_hierarchy: true
files:
  - source: /build/en/*.html
    translation: /build/%two_letters_code%/%original_file_name%
    update_option: "update_as_unapproved"
  - source: /build/en/*.json
    translation: /build/%two_letters_code%/%original_file_name%
    update_option: "update_as_unapproved"
