name: Sync Translations
on:
  #schedule:
  #  - cron: '0 0 * * WED'  # Every Wednesday at midnight
  workflow_dispatch:
jobs:
  sync_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Sync NetworkX translations
        uses: Scientific-Python-Translations/translations-sync@main
        with:
          crowdin-project: "NetworkX"
          source-repo: "networkx/website"
          source-path: "build/en/"
          source-ref: "main"
          translations-repo: "Scientific-Python-Translations/networkx-website-translations"
          translations-path: "build/"
          translations-source-path: "build/en/"
          translations-ref: "main"
          translation-percentage: "90"
          approval-percentage: "0"
          use-precommit: "flase"
          create-toml-file: "false"
          create-upstream-pr: "true"
          auto-merge: "true"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
          crowdin-token: ${{ secrets.CROWDIN_TOKEN }}
