name: Sync Content
on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 5 am
  workflow_dispatch:
jobs:
  sync_content:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Networkx Content
        uses: Scientific-Python-Translations/content-sync@main
        with:
          source-repo: "networkx/website"
          source-path: "build/en/"
          source-ref: "main"
          translations-repo: "Scientific-Python-Translations/networkx-website-translations"
          translations-path: "build/"
          translations-source-path: "build/en/"
          translations-ref: "main"
          auto-merge: "true"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
